<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Exact spec: Patients, Dentists, Treatment Rooms (Box), Visits, Pathologies,
 * Teeth, Odontogram_Details, Documents, Treatment. No optional Materials/Suppliers.
 */
final class Version20260220110000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schema: patients, dentists, treatment_rooms, visits, treatment, pathologies, teeth, odontogram_details, documents';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS odontogram_details CASCADE');
        $this->addSql('DROP TABLE IF EXISTS visits CASCADE');
        $this->addSql('DROP TABLE IF EXISTS radiographs CASCADE');
        $this->addSql('DROP TABLE IF EXISTS documents CASCADE');
        $this->addSql('DROP TABLE IF EXISTS appointment CASCADE');
        $this->addSql('DROP TABLE IF EXISTS patients CASCADE');
        $this->addSql('DROP TABLE IF EXISTS dentists CASCADE');
        $this->addSql('DROP TABLE IF EXISTS doctor CASCADE');
        $this->addSql('DROP TABLE IF EXISTS treatment_rooms CASCADE');
        $this->addSql('DROP TABLE IF EXISTS box CASCADE');
        $this->addSql('DROP TABLE IF EXISTS boxes CASCADE');
        $this->addSql('DROP TABLE IF EXISTS treatment CASCADE');
        $this->addSql('DROP TABLE IF EXISTS treatments CASCADE');
        $this->addSql('DROP TABLE IF EXISTS pathologies CASCADE');
        $this->addSql('DROP TABLE IF EXISTS pathology CASCADE');
        $this->addSql('DROP TABLE IF EXISTS teeth CASCADE');
        $this->addSql('DROP TABLE IF EXISTS tooth CASCADE');
        $this->addSql('DROP TABLE IF EXISTS odontogram_detail CASCADE');
        $this->addSql('DROP TABLE IF EXISTS users CASCADE');

        $this->addSql('CREATE TABLE patients (patient_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, national_id VARCHAR(20) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, social_security_number VARCHAR(50) DEFAULT NULL, telephone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, billing_information TEXT DEFAULT NULL, reason_for_consultation TEXT DEFAULT NULL, family_history TEXT DEFAULT NULL, health_status TEXT DEFAULT NULL, lifestyle_habits TEXT DEFAULT NULL, allergy_medications TEXT DEFAULT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (patient_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2CCC2E2C7F8F253B ON patients (national_id)');
        $this->addSql('CREATE INDEX idx_patient_national_id ON patients (national_id)');
        $this->addSql('CREATE INDEX idx_patient_email ON patients (email)');

        $this->addSql('CREATE TABLE dentists (doctor_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(200) NOT NULL, specialty VARCHAR(100) NOT NULL, assigned_day_of_week VARCHAR(20) NOT NULL, telephone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (doctor_id))');
        $this->addSql('CREATE INDEX idx_dentist_email ON dentists (email)');

        $this->addSql('CREATE TABLE treatment_rooms (id_box INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, box_name VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, capacity INT DEFAULT 2 NOT NULL, PRIMARY KEY (id_box))');
        $this->addSql('CREATE INDEX idx_box_status ON treatment_rooms (status)');

        $this->addSql('CREATE TABLE treatment (id_treatment INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, treatment_name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, estimated_duration VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id_treatment))');
        $this->addSql('CREATE INDEX idx_treatment_name ON treatment (treatment_name)');

        $this->addSql('CREATE TABLE visits (id_visit INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_patient INT NOT NULL, id_doctor INT NOT NULL, id_box INT NOT NULL, id_treatment INT DEFAULT NULL, date_visit DATE NOT NULL, time_visit TIME(0) WITHOUT TIME ZONE NOT NULL, reason_for_consultation TEXT DEFAULT NULL, observations TEXT DEFAULT NULL, PRIMARY KEY (id_visit))');
        $this->addSql('CREATE INDEX idx_visit_patient ON visits (id_patient)');
        $this->addSql('CREATE INDEX idx_visit_doctor ON visits (id_doctor)');
        $this->addSql('CREATE INDEX idx_visit_box ON visits (id_box)');
        $this->addSql('CREATE INDEX idx_visit_treatment ON visits (id_treatment)');
        $this->addSql('CREATE INDEX idx_visit_date ON visits (date_visit)');
        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EA6B899279 FOREIGN KEY (id_patient) REFERENCES patients (patient_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EA1CE0A142 FOREIGN KEY (id_doctor) REFERENCES dentists (doctor_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EAD8177B3F FOREIGN KEY (id_box) REFERENCES treatment_rooms (id_box) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EA471C0366 FOREIGN KEY (id_treatment) REFERENCES treatment (id_treatment) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE pathologies (pathology_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(100) NOT NULL, protocol_color VARCHAR(50) NOT NULL, PRIMARY KEY (pathology_id))');
        $this->addSql('CREATE INDEX idx_pathology_description ON pathologies (description)');

        $this->addSql('CREATE TABLE teeth (tooth_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(50) NOT NULL, PRIMARY KEY (tooth_id))');
        $this->addSql('CREATE INDEX idx_tooth_description ON teeth (description)');

        $this->addSql('CREATE TABLE odontogram_details (detail_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visit_id INT NOT NULL, tooth_id INT NOT NULL, pathology_id INT NOT NULL, tooth_surface VARCHAR(50) NOT NULL, coordinates_3d JSON DEFAULT NULL, PRIMARY KEY (detail_id))');
        $this->addSql('CREATE INDEX idx_odontogram_visit ON odontogram_details (visit_id)');
        $this->addSql('CREATE INDEX idx_odontogram_tooth ON odontogram_details (tooth_id)');
        $this->addSql('CREATE INDEX idx_odontogram_pathology ON odontogram_details (pathology_id)');
        $this->addSql('ALTER TABLE odontogram_details ADD CONSTRAINT FK_BE25053C75FA0FF2 FOREIGN KEY (visit_id) REFERENCES visits (id_visit) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE odontogram_details ADD CONSTRAINT FK_BE25053CA2A44441 FOREIGN KEY (tooth_id) REFERENCES teeth (tooth_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE odontogram_details ADD CONSTRAINT FK_BE25053CCE86795D FOREIGN KEY (pathology_id) REFERENCES pathologies (pathology_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE documents (image_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, patient_id INT NOT NULL, type VARCHAR(50) NOT NULL, file_path VARCHAR(500) NOT NULL, capture_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (image_id))');
        $this->addSql('CREATE INDEX idx_document_patient ON documents (patient_id)');
        $this->addSql('CREATE INDEX idx_document_capture_date ON documents (capture_date)');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_DBBFEFE86B899279 FOREIGN KEY (patient_id) REFERENCES patients (patient_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE odontogram_details DROP CONSTRAINT FK_BE25053C75FA0FF2');
        $this->addSql('ALTER TABLE odontogram_details DROP CONSTRAINT FK_BE25053CA2A44441');
        $this->addSql('ALTER TABLE odontogram_details DROP CONSTRAINT FK_BE25053CCE86795D');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT FK_DBBFEFE86B899279');
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EA6B899279');
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EA1CE0A142');
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EAD8177B3F');
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EA471C0366');
        $this->addSql('DROP TABLE patients');
        $this->addSql('DROP TABLE dentists');
        $this->addSql('DROP TABLE treatment_rooms');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE visits');
        $this->addSql('DROP TABLE pathologies');
        $this->addSql('DROP TABLE teeth');
        $this->addSql('DROP TABLE odontogram_details');
        $this->addSql('DROP TABLE documents');
    }
}
