<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260304214053 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

 public function up(Schema $schema): void
{
    // 1. ELIMINAR PRIMERO LAS RESTRICCIONES (Foreign Keys) QUE BLOQUEAN
    // Esto suelta los "anclajes" de la tabla odontogram
    $this->addSql('ALTER TABLE odontogram DROP CONSTRAINT IF EXISTS fk_251bf940a2a44441');
    $this->addSql('ALTER TABLE odontogram DROP CONSTRAINT IF EXISTS fk_251bf940ce86795d');

    // 2. AHORA SÍ PODEMOS BORRAR LA TABLA TOOTH
    $this->addSql('DROP TABLE IF EXISTS tooth CASCADE');

    // 3. LIMPIAR LAS COLUMNAS VIEJAS DE ODONTOGRAM
    $this->addSql('ALTER TABLE odontogram DROP COLUMN IF EXISTS tooth_surface');
    $this->addSql('ALTER TABLE odontogram DROP COLUMN IF EXISTS tooth_id');
    $this->addSql('ALTER TABLE odontogram DROP COLUMN IF EXISTS pathology_id');

    // 4. CREAR LAS NUEVAS TABLAS
    $this->addSql('CREATE TABLE odontograma_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tooth_number INT NOT NULL, odontograma_id INT NOT NULL, pathology_id INT NOT NULL, PRIMARY KEY (id))');
    $this->addSql('CREATE TABLE tooth_face (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, face_name VARCHAR(10) NOT NULL, odontograma_detail_id INT NOT NULL, PRIMARY KEY (id))');

    // 5. AÑADIR LAS NUEVAS RELACIONES
    $this->addSql('ALTER TABLE odontograma_detail ADD CONSTRAINT FK_8B71D7E9F8ED5CE7 FOREIGN KEY (odontograma_id) REFERENCES odontogram (id) NOT DEFERRABLE');
    $this->addSql('ALTER TABLE odontograma_detail ADD CONSTRAINT FK_8B71D7E9CE86795D FOREIGN KEY (pathology_id) REFERENCES pathology (id) NOT DEFERRABLE');
    $this->addSql('ALTER TABLE tooth_face ADD CONSTRAINT FK_FA2992F9E8457812 FOREIGN KEY (odontograma_detail_id) REFERENCES odontograma_detail (id) NOT DEFERRABLE');
    
    $this->addSql('CREATE INDEX IDX_8B71D7E9F8ED5CE7 ON odontograma_detail (odontograma_id)');
    $this->addSql('CREATE INDEX IDX_8B71D7E9CE86795D ON odontograma_detail (pathology_id)');
    $this->addSql('CREATE INDEX IDX_FA2992F9E8457812 ON tooth_face (odontograma_detail_id)');
}
    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE tooth (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tooth_id INT NOT NULL, description VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE odontograma_detail DROP CONSTRAINT FK_8B71D7E9F8ED5CE7');
        $this->addSql('ALTER TABLE odontograma_detail DROP CONSTRAINT FK_8B71D7E9CE86795D');
        $this->addSql('DROP TABLE odontograma_detail');
        $this->addSql('DROP TABLE tooth_face');
        $this->addSql('ALTER TABLE odontogram ADD tooth_surface VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE odontogram ADD tooth_id INT NOT NULL');
        $this->addSql('ALTER TABLE odontogram ADD pathology_id INT NOT NULL');
        $this->addSql('ALTER TABLE odontogram ADD CONSTRAINT fk_251bf940a2a44441 FOREIGN KEY (tooth_id) REFERENCES tooth (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE odontogram ADD CONSTRAINT fk_251bf940ce86795d FOREIGN KEY (pathology_id) REFERENCES pathology (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_251bf940ce86795d ON odontogram (pathology_id)');
        $this->addSql('CREATE INDEX idx_251bf940a2a44441 ON odontogram (tooth_id)');
    }
}
