<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates core schema in English: patients, dentists, boxes, treatments, visits,
 * pathologies, teeth, odontogram_details, radiographies. No suppliers/materials/protocols.
 */
final class Version20260219152131 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create schema in English (patients, dentists, boxes, treatments, visits, pathologies, teeth, odontogram_details, radiographies)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE patients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dni VARCHAR(20) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, social_security_number VARCHAR(50) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, billing_data TEXT DEFAULT NULL, consultation_reason TEXT DEFAULT NULL, family_history TEXT DEFAULT NULL, health_status TEXT DEFAULT NULL, lifestyle_habits TEXT DEFAULT NULL, medication_allergies TEXT DEFAULT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2CCC2E2C7F8F253B ON patients (dni)');
        $this->addSql('CREATE INDEX idx_patient_dni ON patients (dni)');
        $this->addSql('CREATE INDEX idx_patient_email ON patients (email)');

        $this->addSql('CREATE TABLE dentists (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, specialty VARCHAR(100) NOT NULL, assigned_weekday VARCHAR(20) NOT NULL, phone VARCHAR(50) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_dentist_email ON dentists (email)');

        $this->addSql('CREATE TABLE boxes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, capacity INT DEFAULT 2 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_box_status ON boxes (status)');

        $this->addSql('CREATE TABLE treatments (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_treatment_name ON treatments (name)');

        $this->addSql('CREATE TABLE visits (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visit_date DATE NOT NULL, visit_time TIME(0) WITHOUT TIME ZONE NOT NULL, consultation_reason TEXT DEFAULT NULL, observations TEXT DEFAULT NULL, patient_id INT NOT NULL, dentist_id INT NOT NULL, box_id INT NOT NULL, treatment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_visit_patient ON visits (patient_id)');
        $this->addSql('CREATE INDEX idx_visit_dentist ON visits (dentist_id)');
        $this->addSql('CREATE INDEX idx_visit_box ON visits (box_id)');
        $this->addSql('CREATE INDEX idx_visit_treatment ON visits (treatment_id)');
        $this->addSql('CREATE INDEX idx_visit_date ON visits (visit_date)');

        $this->addSql('CREATE TABLE pathologies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(100) NOT NULL, protocol_color VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_pathology_description ON pathologies (description)');

        $this->addSql('CREATE TABLE teeth (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(10) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_tooth_description ON teeth (description)');
        $this->addSql('CREATE INDEX idx_tooth_position ON teeth (position)');

        $this->addSql('CREATE TABLE odontogram_details (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tooth_face VARCHAR(50) NOT NULL, coordinates_3d JSON DEFAULT NULL, visit_id INT NOT NULL, tooth_id INT NOT NULL, pathology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_odontogram_visit ON odontogram_details (visit_id)');
        $this->addSql('CREATE INDEX idx_odontogram_tooth ON odontogram_details (tooth_id)');
        $this->addSql('CREATE INDEX idx_odontogram_pathology ON odontogram_details (pathology_id)');

        $this->addSql('CREATE TABLE radiographies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, file_path VARCHAR(500) NOT NULL, capture_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_radiography_patient ON radiographies (patient_id)');
        $this->addSql('CREATE INDEX idx_radiography_date ON radiographies (capture_date)');

        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EA6B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EA1CE0A142 FOREIGN KEY (dentist_id) REFERENCES dentists (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EAD8177B3F FOREIGN KEY (box_id) REFERENCES boxes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE visits ADD CONSTRAINT FK_444839EA471C0366 FOREIGN KEY (treatment_id) REFERENCES treatments (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE odontogram_details ADD CONSTRAINT FK_BE25053C75FA0FF2 FOREIGN KEY (visit_id) REFERENCES visits (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE odontogram_details ADD CONSTRAINT FK_BE25053CA2A44441 FOREIGN KEY (tooth_id) REFERENCES teeth (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE odontogram_details ADD CONSTRAINT FK_BE25053CCE86795D FOREIGN KEY (pathology_id) REFERENCES pathologies (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE radiographies ADD CONSTRAINT FK_DBBFEFE86B899279 FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EA6B899279');
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EA1CE0A142');
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EAD8177B3F');
        $this->addSql('ALTER TABLE visits DROP CONSTRAINT FK_444839EA471C0366');
        $this->addSql('ALTER TABLE odontogram_details DROP CONSTRAINT FK_BE25053C75FA0FF2');
        $this->addSql('ALTER TABLE odontogram_details DROP CONSTRAINT FK_BE25053CA2A44441');
        $this->addSql('ALTER TABLE odontogram_details DROP CONSTRAINT FK_BE25053CCE86795D');
        $this->addSql('ALTER TABLE radiographies DROP CONSTRAINT FK_DBBFEFE86B899279');
        $this->addSql('DROP TABLE patients');
        $this->addSql('DROP TABLE dentists');
        $this->addSql('DROP TABLE boxes');
        $this->addSql('DROP TABLE treatments');
        $this->addSql('DROP TABLE visits');
        $this->addSql('DROP TABLE pathologies');
        $this->addSql('DROP TABLE teeth');
        $this->addSql('DROP TABLE odontogram_details');
        $this->addSql('DROP TABLE radiographies');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
