<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311160751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visit_date DATE NOT NULL, visit_time TIME(0) WITHOUT TIME ZONE NOT NULL, consultation_reason VARCHAR(255) NOT NULL, observations TEXT NOT NULL, status VARCHAR(20) NOT NULL, duration_minutes INT NOT NULL, patient_id INT NOT NULL, doctor_id INT NOT NULL, box_id INT NOT NULL, treatment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE38F8446B899279 ON appointment (patient_id)');
        $this->addSql('CREATE INDEX IDX_FE38F84487F4FB17 ON appointment (doctor_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844D8177B3F ON appointment (box_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844471C0366 ON appointment (treatment_id)');
        $this->addSql('CREATE TABLE box (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, box_name VARCHAR(50) NOT NULL, status BOOLEAN NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE doctor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_names VARCHAR(100) NOT NULL, specialty VARCHAR(100) NOT NULL, assigned_weekday VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, file_path VARCHAR(255) NOT NULL, capture_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT DEFAULT NULL, patient_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A766B899279 ON document (patient_id)');
        $this->addSql('CREATE INDEX idx_document_capture_date ON document (capture_date)');
        $this->addSql('CREATE TABLE odontogram (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, visit_id INT NOT NULL, treatment_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_251BF94075FA0FF2 ON odontogram (visit_id)');
        $this->addSql('CREATE INDEX IDX_251BF940471C0366 ON odontogram (treatment_id)');
        $this->addSql('CREATE TABLE odontograma_detail (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tooth_number INT NOT NULL, odontograma_id INT NOT NULL, pathology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8B71D7E9F8ED5CE7 ON odontograma_detail (odontograma_id)');
        $this->addSql('CREATE INDEX IDX_8B71D7E9CE86795D ON odontograma_detail (pathology_id)');
        $this->addSql('CREATE TABLE pathology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, protocol_color VARCHAR(7) NOT NULL, visual_type VARCHAR(20) DEFAULT NULL, treatment_id INT NOT NULL, pathology_type_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DC171E93471C0366 ON pathology (treatment_id)');
        $this->addSql('CREATE INDEX IDX_DC171E93753C9914 ON pathology (pathology_type_id)');
        $this->addSql('CREATE TABLE pathology_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) DEFAULT NULL, default_duration INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identity_document VARCHAR(50) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, ss_number VARCHAR(30) DEFAULT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(100) NOT NULL, address TEXT NOT NULL, consultation_reason TEXT NOT NULL, family_history TEXT NOT NULL, health_status TEXT NOT NULL, lifestyle_habits TEXT NOT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medication_allergies TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tooth_face (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, face_name VARCHAR(10) NOT NULL, odontograma_detail_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4AA349829093CE6 ON tooth_face (odontograma_detail_id)');
        $this->addSql('CREATE TABLE treatment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, treatment_name VARCHAR(100) NOT NULL, description TEXT NOT NULL, estimated_duration INT DEFAULT NULL, last_odontogram_id INT DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, scheduling_notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8446B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84487F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844D8177B3F FOREIGN KEY (box_id) REFERENCES box (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A766B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE odontogram ADD CONSTRAINT FK_251BF94075FA0FF2 FOREIGN KEY (visit_id) REFERENCES appointment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE odontogram ADD CONSTRAINT FK_251BF940471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE odontograma_detail ADD CONSTRAINT FK_8B71D7E9F8ED5CE7 FOREIGN KEY (odontograma_id) REFERENCES odontogram (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE odontograma_detail ADD CONSTRAINT FK_8B71D7E9CE86795D FOREIGN KEY (pathology_id) REFERENCES pathology (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pathology ADD CONSTRAINT FK_DC171E93471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pathology ADD CONSTRAINT FK_DC171E93753C9914 FOREIGN KEY (pathology_type_id) REFERENCES pathology_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tooth_face ADD CONSTRAINT FK_F4AA349829093CE6 FOREIGN KEY (odontograma_detail_id) REFERENCES odontograma_detail (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F8446B899279');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F84487F4FB17');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844D8177B3F');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844471C0366');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A766B899279');
        $this->addSql('ALTER TABLE odontogram DROP CONSTRAINT FK_251BF94075FA0FF2');
        $this->addSql('ALTER TABLE odontogram DROP CONSTRAINT FK_251BF940471C0366');
        $this->addSql('ALTER TABLE odontograma_detail DROP CONSTRAINT FK_8B71D7E9F8ED5CE7');
        $this->addSql('ALTER TABLE odontograma_detail DROP CONSTRAINT FK_8B71D7E9CE86795D');
        $this->addSql('ALTER TABLE pathology DROP CONSTRAINT FK_DC171E93471C0366');
        $this->addSql('ALTER TABLE pathology DROP CONSTRAINT FK_DC171E93753C9914');
        $this->addSql('ALTER TABLE tooth_face DROP CONSTRAINT FK_F4AA349829093CE6');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE box');
        $this->addSql('DROP TABLE doctor');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE odontogram');
        $this->addSql('DROP TABLE odontograma_detail');
        $this->addSql('DROP TABLE pathology');
        $this->addSql('DROP TABLE pathology_type');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE tooth_face');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
