<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Remove optional Supplies module: drop materials and treatment_material_protocol.
 * (Materiales, Proveedores, Protocolo_Material — optional module not used.)
 */
final class Version20260220180000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Drop optional Supplies module tables (treatment_material_protocol, materials)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS treatment_material_protocol CASCADE');
        $this->addSql('DROP TABLE IF EXISTS materials CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE materials (material_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (material_id))');
        $this->addSql('CREATE TABLE treatment_material_protocol (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, treatment_id INT NOT NULL, material_id INT NOT NULL, quantity_required INT DEFAULT 1 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_treatment_material ON treatment_material_protocol (treatment_id, material_id)');
        $this->addSql('ALTER TABLE treatment_material_protocol ADD CONSTRAINT FK_protocol_treatment FOREIGN KEY (treatment_id) REFERENCES treatment (id_treatment) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE treatment_material_protocol ADD CONSTRAINT FK_protocol_material FOREIGN KEY (material_id) REFERENCES materials (material_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
