<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311144839 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pathology_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) DEFAULT NULL, default_duration INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE appointment ADD duration_minutes INT NOT NULL');
        $this->addSql('ALTER TABLE pathology ADD pathology_type_id INT NOT NULL');
        $this->addSql('ALTER TABLE pathology ADD CONSTRAINT FK_DC171E93F282833D FOREIGN KEY (pathology_type_id) REFERENCES pathology_type (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_DC171E93F282833D ON pathology (pathology_type_id_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE pathology_type');
        $this->addSql('ALTER TABLE appointment DROP duration_minutes');
        $this->addSql('ALTER TABLE pathology DROP CONSTRAINT FK_DC171E93F282833D');
        $this->addSql('DROP INDEX IDX_DC171E93F282833D');
        $this->addSql('ALTER TABLE pathology DROP pathology_type_id');
    }
}
