<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223122413 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appointment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, visit_date DATE NOT NULL, visit_time TIME(0) WITHOUT TIME ZONE NOT NULL, consultation_reason VARCHAR(255) NOT NULL, observations TEXT NOT NULL, status VARCHAR(20) NOT NULL, patient_id INT NOT NULL, doctor_id INT NOT NULL, box_id INT NOT NULL, treatment_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FE38F8446B899279 ON appointment (patient_id)');
        $this->addSql('CREATE INDEX IDX_FE38F84487F4FB17 ON appointment (doctor_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844D8177B3F ON appointment (box_id)');
        $this->addSql('CREATE INDEX IDX_FE38F844471C0366 ON appointment (treatment_id)');
        $this->addSql('CREATE TABLE box (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, box_name VARCHAR(50) NOT NULL, status BOOLEAN NOT NULL, capacity INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE doctor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_names VARCHAR(100) NOT NULL, specialty VARCHAR(100) NOT NULL, assigned_weekday VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, file_path VARCHAR(255) NOT NULL, capture_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, description TEXT DEFAULT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A766B899279 ON document (patient_id)');
        $this->addSql('CREATE TABLE odontogram (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tooth_surface VARCHAR(50) DEFAULT NULL, status VARCHAR(20) NOT NULL, visit_id INT NOT NULL, tooth_id INT NOT NULL, pathology_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_251BF94075FA0FF2 ON odontogram (visit_id)');
        $this->addSql('CREATE INDEX IDX_251BF940A2A44441 ON odontogram (tooth_id)');
        $this->addSql('CREATE INDEX IDX_251BF940CE86795D ON odontogram (pathology_id)');
        $this->addSql('CREATE TABLE pathology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, protocol_color VARCHAR(7) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identity_document VARCHAR(50) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, ss_number VARCHAR(30) DEFAULT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(100) NOT NULL, address TEXT NOT NULL, consultation_reason TEXT NOT NULL, family_history TEXT NOT NULL, health_status TEXT NOT NULL, lifestyle_habits TEXT NOT NULL, registration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medication_allergies TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tooth (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tooth_id INT NOT NULL, description VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE treatment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, treatment_name VARCHAR(100) NOT NULL, description TEXT NOT NULL, estimated_duration INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F8446B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F84487F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctor (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844D8177B3F FOREIGN KEY (box_id) REFERENCES box (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE appointment ADD CONSTRAINT FK_FE38F844471C0366 FOREIGN KEY (treatment_id) REFERENCES treatment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A766B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE odontogram ADD CONSTRAINT FK_251BF94075FA0FF2 FOREIGN KEY (visit_id) REFERENCES appointment (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE odontogram ADD CONSTRAINT FK_251BF940A2A44441 FOREIGN KEY (tooth_id) REFERENCES tooth (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE odontogram ADD CONSTRAINT FK_251BF940CE86795D FOREIGN KEY (pathology_id) REFERENCES pathology (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F8446B899279');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F84487F4FB17');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844D8177B3F');
        $this->addSql('ALTER TABLE appointment DROP CONSTRAINT FK_FE38F844471C0366');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A766B899279');
        $this->addSql('ALTER TABLE odontogram DROP CONSTRAINT FK_251BF94075FA0FF2');
        $this->addSql('ALTER TABLE odontogram DROP CONSTRAINT FK_251BF940A2A44441');
        $this->addSql('ALTER TABLE odontogram DROP CONSTRAINT FK_251BF940CE86795D');
        $this->addSql('DROP TABLE appointment');
        $this->addSql('DROP TABLE box');
        $this->addSql('DROP TABLE doctor');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE odontogram');
        $this->addSql('DROP TABLE pathology');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE tooth');
        $this->addSql('DROP TABLE treatment');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
